version: '3.8'
services:
  frontend:
    image: bestlalala/autobot-app:1.0.3
    platform: linux/amd64
    ports:
      - "80:80"
    environment:
      - VITE_AUTH_BASE_URL=${APP_URL}:8080
      - VITE_CHAT_BASE_URL=${APP_URL}:8080
    depends_on:
      - backend

  backend:
    image: blooming12/autobot:1.0.5.1
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_PW=${DB_PW}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=us-east-1
      # - AWS_MODEL_ARN=
      # - AWS_KNOWLEDGEBASE_ID=PT7IJMU5EZ
      # - AWS_GUARDRAIL_ID=
      # - AWS_GUARDRAIL_VERSION=
      - CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:8080,http://localhost:5173,${APP_URL},${APP_URL}:80,${APP_URL}:8080
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: blooming12/chatpsql:1.0.1
    platform: linux/amd64
    environment:
      - POSTGRES_PASSWORD=${DB_PW}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: 
